### ISSUE TITLE
Fix character/series search 

### ISSUE THREAD

**Issue by Tunnelbliick** [mirage-software/Kabooty#26]

**Comment by lvdlee** [comment]
What was wrong with this again? Seems to work fine as things stand.

**Comment by Tunnelbliick** [comment]
@lvdlee had todo with fizzbuzz search returning no always the right characters when you only partually fill the name out.

Like Tun for Tunnelblick etc. i think was main cause for concern. Since people sometimes didnt find their character even tho they searched for them.

**Comment by Tunnelbliick** [comment]
Hanvt seen this come up in a while tho so might wanna close this
