### ISSUE TITLE
Potentionally improve Search

### ISSUE THREAD

**Issue by Tunnelbliick** [mirage-software/Kabooty#70]
Allowing for both character and series at the same time tho im not sure how to quite do with from a single search query.

like "Lin Arknights" currently returns nothing.

**Comment by Tunnelbliick** [comment]
@lvdlee dunno if something like this is possible, without doing some whacky regex shit.

**Comment by lvdlee** [comment]
Maybe postgres full text search feature supports smth like this

**Comment by Tunnelbliick** [comment]
https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search

looks a bit grim
